---
references:
- id: conf/bueroautomation/HeinST85
  type: paper-conference
  author:
  - family: Hein
    given: Hans-Werner
  - family: Smith
    given: Scott R.
  - family: Thomas
    given: Christoph G.
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: Konzeptionelle grundlage einer wissensbasierten mensch-maschine-schnittstelle
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '260-268'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/Peuckert85
  type: paper-conference
  author:
  - family: Peuckert
    given: Heribert
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: Auf dem weg zur integrierten bürokommunikation
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '233-240'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/Schumann85
  type: paper-conference
  author:
  - family: Schumann
    given: Matthias
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: Computergestützte eingangspostbearbeitung - überblick über den stand und
    weitere forschungsaufgaben
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '70-87'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/TruckenmullerNF85
  type: paper-conference
  author:
  - family: Truckenmüller
    given: Till W.
  - family: Niemeier
    given: Joachim
  - family: Fähnrich
    given: Klaus-Peter
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: Videokonferenzen - entscheidender schritt in der unterstützung von managern
    und fachspezialisten durch integrierte bürosysteme
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '241-259'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/EffelsbergL85
  type: paper-conference
  author:
  - family: Effelsberg
    given: Wolfgang
  - family: Lamersdorf
    given: Winfried
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: Strukturierung von büroaktivitäten
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '192-214'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/Wedekind85
  type: paper-conference
  author:
  - family: Wedekind
    given: Hartmut
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: Büroautomation - eine anthropotechnische aufgabe
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '8-33'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/NiehuisV85
  type: paper-conference
  author:
  - family: Niehuis
    given: S.
  - family: Victor
    given: Frank
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: Modellierung von büroprozeduren
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '88-107'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/HorakK85
  type: paper-conference
  author:
  - family: Horak
    given: Wolfgang
  - family: Krönert
    given: Günther
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: Konzept eines editors basierend auf der büro-dokumentenarchitektur eCMA 101
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '62-69'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/PradelSDL85
  type: paper-conference
  author:
  - family: Prädel
    given: U.
  - family: Schlageter
    given: Gunter
  - family: Dadam
    given: Peter
  - family: Lum
    given: Vincent Y.
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: Index management und concurrency control in integrierten informationssystemen
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '146-171'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/Chemin85
  type: paper-conference
  author:
  - family: Chemin
    given: L.
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: Implementation of a distributed message system on a local network
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '269-279'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/AppelrathE85
  type: paper-conference
  author:
  - family: Appelrath
    given: Hans-Jürgen
  - family: Ester
    given: Martin
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: 'Integrity in a knowledge based office information system: Modeling with
    extended sDM and implementation with prolog'
  title-short: Integrity in a knowledge based office information system
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '172-191'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/Gehne85
  type: paper-conference
  author:
  - family: Gehne
    given: Wolfgang
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: IBM bürokommunikation
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '34-39'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/Gray85
  type: paper-conference
  author:
  - family: Gray
    given: Jim
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: Why do computer stop and what can be about it?
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '128-145'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/Blumenfeld85
  type: paper-conference
  author:
  - family: Blumenfeld
    given: Matthias
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: Dokumentenarchitektur und austauschformate
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '40-61'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/TsichritzisN85
  type: paper-conference
  author:
  - family: Tsichritzis
    given: Dennis
  - family: Nierstrasz
    given: Oscar
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: End user objects
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '215-232'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/RonzaniTZ85
  type: paper-conference
  author:
  - family: Ronzani
    given: S.
  - family: Tisato
    given: Francesco
  - family: Zicari
    given: Roberto
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: An office specification language based on path expressions
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '108-127'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/Kay85
  type: paper-conference
  author:
  - family: Kay
    given: Alan C.
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: The user interface as a theatrical mirror
  container-title: Büroautomation
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  page: '280-280'
  volume: '25'
  ISBN: '3-519-02444-6'

- id: conf/bueroautomation/1985
  type: book
  editor:
  - family: Wedekind
    given: Hartmut
  issued:
  - year: '1985'
  title: Büroautomation ’85, tagung iV/1985 des german chapter of the aCM vom 2. bis
    4.10.1985 in erlangen
  collection-title: Berichte des german chapter of the aCM
  publisher: Teubner
  volume: '25'
  ISBN: '3-519-02444-6'
...
