---
references:
- id: conf/cybersecurity/VriesHBD12
  type: paper-conference
  author:
  - family: Vries
    given: Johannes
    dropping-particle: de
  - family: Hoogstraaten
    given: Hans
  - family: Berg
    given: Jan
    dropping-particle: van den
  - family: Daskapan
    given: Semir
  issued:
  - year: '2012'
  title: 'Systems for detecting advanced persistent threats: A development roadmap
    using intelligent data analysis'
  title-short: Systems for detecting advanced persistent threats
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '54-61'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.14
  DOI: 10.1109/CyberSecurity.2012.14
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/HassanG12
  type: paper-conference
  author:
  - family: Hassan
    given: Sharif
  - family: Guha
    given: Ratan
  issued:
  - year: '2012'
  title: Security and integrity analysis using indicators
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '127-135'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.23
  DOI: 10.1109/CyberSecurity.2012.23
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/DolevGK12
  type: paper-conference
  author:
  - family: Dolev
    given: Shlomi
  - family: Gilboa
    given: Niv
  - family: Kopeetsky
    given: Marina
  issued:
  - year: '2012'
  title: Permanent revocation in attribute based broadcast encryption
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '203-208'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.33
  DOI: 10.1109/CyberSecurity.2012.33
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/FerebeeDW12
  type: paper-conference
  author:
  - family: Ferebee
    given: Denise
  - family: Dasgupta
    given: Dipankar
  - family: Wu
    given: Qishi
  issued:
  - year: '2012'
  title: A cyber-security storm mAP
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '93-102'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.19
  DOI: 10.1109/CyberSecurity.2012.19
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/ZhouLSAML12
  type: paper-conference
  author:
  - family: Zhou
    given: Bo
  - family: Llewellyn-Jones
    given: David
  - family: Shi
    given: Qi
  - family: Asim
    given: Muhammad
  - family: Merabti
    given: Madjid
  - family: Lamb
    given: David J.
  issued:
  - year: '2012'
  title: A compose language-based framework for secure service composition
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '195-202'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.32
  DOI: 10.1109/CyberSecurity.2012.32
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/SanchezD12
  type: paper-conference
  author:
  - family: Sanchez
    given: Fernando
  - family: Duan
    given: Zhenhai
  issued:
  - year: '2012'
  title: A sender-centric approach to detecting phishing emails
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '32-39'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.11
  DOI: 10.1109/CyberSecurity.2012.11
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/AtkinsonWBH12
  type: paper-conference
  author:
  - family: Atkinson
    given: Simon Reay
  - family: Walker
    given: David
  - family: Beaulne
    given: Kevin
  - family: Hossain
    given: Liaquat
  issued:
  - year: '2012'
  title: Cyber - transparencies, assurance and deterrence
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '119-126'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.22
  DOI: 10.1109/CyberSecurity.2012.22
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/BayagaF12
  type: paper-conference
  author:
  - family: Bayaga
    given: Anass
  - family: Flowerday
    given: Stephen
  issued:
  - year: '2012'
  title: Principal causes of information communication technology (iCT) risk failure
    in an sME
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '152-156'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.26
  DOI: 10.1109/CyberSecurity.2012.26
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/AlEroudK12
  type: paper-conference
  author:
  - family: AlEroud
    given: Ahmed
  - family: Karabatis
    given: George
  issued:
  - year: '2012'
  title: A contextual anomaly detection approach to discover zero-day attacks
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '40-45'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.12
  DOI: 10.1109/CyberSecurity.2012.12
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/BaumeisterDDT12
  type: paper-conference
  author:
  - family: Baumeister
    given: Todd
  - family: Dong
    given: Yingfei
  - family: Duan
    given: Zhenhai
  - family: Tian
    given: Guanyu
  issued:
  - year: '2012'
  title: A routing table insertion (rTI) attack on freenet
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '8-15'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.8
  DOI: 10.1109/CyberSecurity.2012.8
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/2012
  type: book
  issued:
  - year: '2012'
  title: 2012 aSE international conference on cyber security, alexandria, vA, uSA,
    december 14-16, 2012
  publisher: IEEE Computer Society
  URL: http://ieeexplore.ieee.org/xpl/mostRecentIssue.jsp?punumber=6542298
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/ZawoadH12
  type: paper-conference
  author:
  - family: Zawoad
    given: Shams
  - family: Hasan
    given: Ragib
  issued:
  - year: '2012'
  title: 'I have the proof: Providing proofs of past data possession in cloud forensics'
  title-short: I have the proof
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '75-82'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.17
  DOI: 10.1109/CyberSecurity.2012.17
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/PatilZLR12
  type: paper-conference
  author:
  - family: Patil
    given: Pallavi
  - family: Zavarsky
    given: Pavol
  - family: Lindskog
    given: Dale
  - family: Ruhl
    given: Ron
  issued:
  - year: '2012'
  title: Fault tree analysis of accidental insider security events
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '113-118'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.21
  DOI: 10.1109/CyberSecurity.2012.21
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/DoyalZY12
  type: paper-conference
  author:
  - family: Doyal
    given: Alex
  - family: Zhan
    given: Justin
  - family: Yu
    given: Huiming Anna
  issued:
  - year: '2012'
  title: Towards defeating dDoS attacks
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '209-212'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.34
  DOI: 10.1109/CyberSecurity.2012.34
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/GasiorY12
  type: paper-conference
  author:
  - family: Gasior
    given: Wade
  - family: Yang
    given: Li
  issued:
  - year: '2012'
  title: Exploring covert channel in android platform
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '173-177'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.29
  DOI: 10.1109/CyberSecurity.2012.29
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/ErbacherH12
  type: paper-conference
  author:
  - family: Erbacher
    given: Robert F.
  - family: Hutchinson
    given: Steve E.
  issued:
  - year: '2012'
  title: Extending case-based reasoning to network alert reporting
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '187-194'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.31
  DOI: 10.1109/CyberSecurity.2012.31
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/RybnicekPRT12
  type: paper-conference
  author:
  - family: Rybnicek
    given: Marlies
  - family: Poisel
    given: Rainer
  - family: Ruzicka
    given: Manfred
  - family: Tjoa
    given: Simon
  issued:
  - year: '2012'
  title: A generic approach to critical infrastructure modeling and simulation
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '144-151'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.25
  DOI: 10.1109/CyberSecurity.2012.25
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/ShimAM12
  type: paper-conference
  author:
  - family: Shim
    given: Woohyun
  - family: Allodi
    given: Luca
  - family: Massacci
    given: Fabio
  issued:
  - year: '2012'
  title: Crime pays if you are just an average hacker
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '62-68'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.15
  DOI: 10.1109/CyberSecurity.2012.15
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/KanampiuZ12
  type: paper-conference
  author:
  - family: Kanampiu
    given: Munene W.
  - family: Zhan
    given: Justin
  issued:
  - year: '2012'
  title: A dynamic covert passive actors detection scheme for a healthy networked
    community
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '178-186'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.30
  DOI: 10.1109/CyberSecurity.2012.30
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/LinS12
  type: paper-conference
  author:
  - family: Lin
    given: Chung-Wei
  - family: Sangiovanni-Vincentelli
    given: Alberto L.
  issued:
  - year: '2012'
  title: Cyber-security for the controller area network (cAN) communication protocol
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '1-7'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.7
  DOI: 10.1109/CyberSecurity.2012.7
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/KulikovaHBP12
  type: paper-conference
  author:
  - family: Kulikova
    given: Olga
  - family: Heil
    given: Ronald
  - family: Berg
    given: Jan
    dropping-particle: van den
  - family: Pieters
    given: Wolter
  issued:
  - year: '2012'
  title: 'Cyber crisis management: A decision-support framework for disclosing security
    incident information'
  title-short: Cyber crisis management
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '103-112'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.20
  DOI: 10.1109/CyberSecurity.2012.20
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/NimgaonkarKG12
  type: paper-conference
  author:
  - family: Nimgaonkar
    given: Satyajeet
  - family: Kotikela
    given: Srujan
  - family: Gomathisankaran
    given: Mahadevan
  issued:
  - year: '2012'
  title: 'CTrust: A framework for secure and trustworthy application execution in
    cloud computing'
  title-short: CTrust
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '24-31'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.10
  DOI: 10.1109/CyberSecurity.2012.10
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/Zseby12
  type: paper-conference
  author:
  - family: Zseby
    given: Tanja
  issued:
  - year: '2012'
  title: Is iPv6 ready for the smart grid?
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '157-164'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.27
  DOI: 10.1109/CyberSecurity.2012.27
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/AbadieW12
  type: paper-conference
  author:
  - family: Abadie
    given: Andre
  - family: Wijesekera
    given: Duminda
  issued:
  - year: '2012'
  title: Leveraging an inventory of the cognitive radio attack surface
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '136-143'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.24
  DOI: 10.1109/CyberSecurity.2012.24
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/DaiSLG12
  type: paper-conference
  author:
  - family: Dai
    given: Jun
  - family: Sun
    given: Xiaoyan
  - family: Liu
    given: Peng
  - family: Giacobe
    given: Nicklaus A.
  issued:
  - year: '2012'
  title: Gaining big picture awareness through an interconnected cross-layer situation
    knowledge reference model
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '83-92'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.18
  DOI: 10.1109/CyberSecurity.2012.18
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/SongMM12
  type: paper-conference
  author:
  - family: Song
    given: Hanchen
  - family: Muelder
    given: Chris
  - family: Ma
    given: Kwan-Liu
  issued:
  - year: '2012'
  title: Crucial nodes centric visual monitoring and analysis of computer networks
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '16-23'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.9
  DOI: 10.1109/CyberSecurity.2012.9
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/KishimotoOYYT12
  type: paper-conference
  author:
  - family: Kishimoto
    given: Kazuya
  - family: Ohira
    given: Kenji
  - family: Yamaguchi
    given: Yukiko
  - family: Yamaki
    given: Hirofumi
  - family: Takakura
    given: Hiroki
  issued:
  - year: '2012'
  title: An adaptive honeypot system to capture iPv6 address scans
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '165-172'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.28
  DOI: 10.1109/CyberSecurity.2012.28
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/GiuraW12
  type: paper-conference
  author:
  - family: Giura
    given: Paul
  - family: Wang
    given: Wei
  issued:
  - year: '2012'
  title: A context-based detection framework for advanced persistent threats
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '69-74'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.16
  DOI: 10.1109/CyberSecurity.2012.16
  ISBN: '978-1-4799-0219-4'

- id: conf/cybersecurity/SkrupskyMBHVZ12
  type: paper-conference
  author:
  - family: Skrupsky
    given: Nazari
  - family: Monshizadeh
    given: Maliheh
  - family: Bisht
    given: Prithvi
  - family: Hinrichs
    given: Timothy L.
  - family: Venkatakrishnan
    given: V. N.
  - family: Zuck
    given: Lenore D.
  issued:
  - year: '2012'
  title: 'WAVES: Automatic synthesis of client-side validation code for web applications'
  title-short: WAVES
  container-title: CyberSecurity
  publisher: IEEE Computer Society
  page: '46-53'
  URL: http://doi.ieeecomputersociety.org/10.1109/CyberSecurity.2012.13
  DOI: 10.1109/CyberSecurity.2012.13
  ISBN: '978-1-4799-0219-4'
...
