---
references:
- id: conf/workflow/JonkerNDV99
  type: paper-conference
  author:
  - family: Jonker
    given: Willem
  - family: Nijenhuis
    given: Wim
  - family: Damen
    given: Zef
  - family: Verwijmeren
    given: Martin
  editor:
  - family: Bussler
    given: Christoph
  issued:
  - year: '1999'
  title: Workflow management systems and cross-organisational logistics
  container-title: Cross-organisational workflow management and co-ordination
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  volume: '17'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-17/Jonker.ps

- id: conf/workflow/EderP99
  type: paper-conference
  author:
  - family: Eder
    given: Johann
  - family: Panagos
    given: Euthimios
  editor:
  - family: Bussler
    given: Christoph
  issued:
  - year: '1999'
  title: Towards distributed workflow process management
  container-title: Cross-organisational workflow management and co-ordination
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  volume: '17'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-17/Panagos/wacc-camera.html

- id: conf/workflow/SchuldtSAS99
  type: paper-conference
  author:
  - family: Schuldt
    given: Heiko
  - family: Schuler
    given: Christoph
  - family: Alonso
    given: Gustavo
  - family: Schek
    given: Hans-Jörg
  editor:
  - family: Dadam
    given: Peter
  issued:
  - year: '1999'
  title: 'Workflows over workflows: Practical experiences with the integration of
    sAP r/3 business workflow in wISE'
  title-short: Workflows over workflows
  container-title: Enterprise-wide and cross-enterprise workflow management
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  page: '65-71'
  volume: '24'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-24/ssas99.pdf

- id: conf/workflow/GillmannWWK99
  type: paper-conference
  author:
  - family: Gillmann
    given: Michael
  - family: Weißenfels
    given: Jeanine
  - family: Weikum
    given: Gerhard
  - family: Kraiss
    given: Achim
  editor:
  - family: Dadam
    given: Peter
  issued:
  - year: '1999'
  title: Performance assessment and configuration of enterprise-wide workflow management
    systems
  container-title: Enterprise-wide and cross-enterprise workflow management
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  page: '18-24'
  volume: '24'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-24/gwwk99.pdf

- id: conf/workflow/AlonsoFLSSW99
  type: paper-conference
  author:
  - family: Alonso
    given: Gustavo
  - family: Fiedler
    given: Ulrich
  - family: Lazcano
    given: Amaia
  - family: Schuldt
    given: Heiko
  - family: Schuler
    given: Christoph
  - family: Weiler
    given: N.
  editor:
  - family: Dadam
    given: Peter
  issued:
  - year: '1999'
  title: 'WISE: An infrastructure for e-commerce'
  title-short: WISE
  container-title: Enterprise-wide and cross-enterprise workflow management
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  page: '2-9'
  volume: '24'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-24/aflssw99.pdf

- id: conf/workflow/1999
  type: book
  editor:
  - family: Dadam
    given: Peter
  issued:
  - year: '1999'
  title: 'Workshop informatik ’99: Enterprise-wide and cross-enterprise workflow
    management: Concepts, systems, applications, paderborn, germany, october 6, 1999'
  title-short: Workshop informatik ’99
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  volume: '24'

- id: conf/workflow/Joeris99
  type: paper-conference
  author:
  - family: Joeris
    given: Gregor
  editor:
  - family: Dadam
    given: Peter
  issued:
  - year: '1999'
  title: Defining flexible workflow execution behaviors
  container-title: Enterprise-wide and cross-enterprise workflow management
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  page: '49-55'
  volume: '24'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-24/joe99.pdf

- id: conf/workflow/LudwigH99
  type: paper-conference
  author:
  - family: Ludwig
    given: Heiko
  - family: Hoffner
    given: Yigal
  editor:
  - family: Bussler
    given: Christoph
  issued:
  - year: '1999'
  title: Contract-based cross-organisational workflows - the crossFlow project
  container-title: Cross-organisational workflow management and co-ordination
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  volume: '17'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-17/Ludwig.ps

- id: conf/workflow/1999wacc
  type: book
  editor:
  - family: Bussler
    given: Christoph
  issued:
  - year: '1999'
  title: Proceedings of the workshop on cross-organisational workflow management and
    co-ordination, san francisco, uSA, february 22, 1999
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  volume: '17'

- id: conf/workflow/ReichertBD99
  type: paper-conference
  author:
  - family: Reichert
    given: Manfred
  - family: Bauer
    given: Thomas
  - family: Dadam
    given: Peter
  editor:
  - family: Dadam
    given: Peter
  issued:
  - year: '1999'
  title: 'Enterprise-wide and cross-enterprise workflow-management: Challenges and
    research issues for adaptive workflows'
  title-short: Enterprise-wide and cross-enterprise workflow-management
  container-title: Enterprise-wide and cross-enterprise workflow management
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  page: '56-64'
  volume: '24'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-24/rbd99.pdf

- id: conf/workflow/Weske99
  type: paper-conference
  author:
  - family: Weske
    given: Mathias
  editor:
  - family: Dadam
    given: Peter
  issued:
  - year: '1999'
  title: Adaptive workflows based on flexible assignment of workflow schemes and workflow
    instances
  container-title: Enterprise-wide and cross-enterprise workflow management
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  page: '42-48'
  volume: '24'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-24/wes99.pdf

- id: conf/workflow/ShepherdsonTO99
  type: paper-conference
  author:
  - family: Shepherdson
    given: John W.
  - family: Thompson
    given: Simon G.
  - family: Odgers
    given: Brian
  editor:
  - family: Bussler
    given: Christoph
  issued:
  - year: '1999'
  title: Cross organisational workflow co-ordinated by software agents
  container-title: Cross-organisational workflow management and co-ordination
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  volume: '17'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-17/Shepherdson/waccWSPosition_1.html

- id: conf/workflow/KreifeltsHW99
  type: paper-conference
  author:
  - family: Kreifelts
    given: Thomas
  - family: Hinrichs
    given: Elke
  - family: Woetzel
    given: Gerd
  editor:
  - family: Bussler
    given: Christoph
  issued:
  - year: '1999'
  title: 'BSCW-flow: Workflow in web-based shared workspaces'
  title-short: BSCW-flow
  container-title: Cross-organisational workflow management and co-ordination
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  volume: '17'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-17/Kreifelts/BSCWflow.html

- id: conf/workflow/Kaiser99
  type: paper-conference
  author:
  - family: Kaiser
    given: Gail E.
  editor:
  - family: Bussler
    given: Christoph
  issued:
  - year: '1999'
  title: 'From oz to treatyMaker: An international alliance for multi-organization
    workflow'
  title-short: From oz to treatyMaker
  container-title: Cross-organisational workflow management and co-ordination
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  volume: '17'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-17/Kaiser.html

- id: conf/workflow/SchuldtPS99
  type: paper-conference
  author:
  - family: Schuldt
    given: Heiko
  - family: Popovici
    given: Andrei
  - family: Schek
    given: Hans-Jörg
  editor:
  - family: Dadam
    given: Peter
  issued:
  - year: '1999'
  title: Give me all i pay for - the need for execution guarantees in electronic commerce
    payments
  container-title: Enterprise-wide and cross-enterprise workflow management
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  page: '10-17'
  volume: '24'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-24/sps99.pdf

- id: conf/workflow/BauerD99
  type: paper-conference
  author:
  - family: Bauer
    given: Thomas
  - family: Dadam
    given: Peter
  editor:
  - family: Dadam
    given: Peter
  issued:
  - year: '1999'
  title: Efficient distributed control of enterprise-wide and cross-enterprise workflows
  container-title: Enterprise-wide and cross-enterprise workflow management
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  page: '25-32'
  volume: '24'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-24/bd99.pdf

- id: conf/workflow/BeringerW99
  type: paper-conference
  author:
  - family: Beringer
    given: Dorothea
  - family: Wiederhold
    given: Gio
  editor:
  - family: Bussler
    given: Christoph
  issued:
  - year: '1999'
  title: Cost estimation in the cPAM access protocol for remote autonomous services
  container-title: Cross-organisational workflow management and co-ordination
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  volume: '17'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-17/Beringer.html

- id: conf/workflow/LindertD99
  type: paper-conference
  author:
  - family: Lindert
    given: Frank
  - family: Deiters
    given: Wolfgang
  editor:
  - family: Dadam
    given: Peter
  issued:
  - year: '1999'
  title: Modelling inter-organizational processes with process model fragments
  container-title: Enterprise-wide and cross-enterprise workflow management
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  page: '33-41'
  volume: '24'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-24/ld99.pdf

- id: conf/workflow/Casati99
  type: paper-conference
  author:
  - family: Casati
    given: Fabio
  editor:
  - family: Bussler
    given: Christoph
  issued:
  - year: '1999'
  title: Semantic interoperability in interorganizational workflows
  container-title: Cross-organisational workflow management and co-ordination
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  volume: '17'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-17/Casati.ps

- id: conf/workflow/HullS99
  type: paper-conference
  author:
  - family: Hull
    given: Richard
  - family: Su
    given: Jianwen
  editor:
  - family: Bussler
    given: Christoph
  issued:
  - year: '1999'
  title: The vortex approach to integration and coordination of workflows
  container-title: Cross-organisational workflow management and co-ordination
  collection-title: CEUR workshop proceedings
  publisher: CEUR-WS.org
  volume: '17'
  URL: http://SunSITE.Informatik.RWTH-Aachen.DE/Publications/CEUR-WS/Vol-17/Hull/index.html
...
